from _typeshed import Incomplete

class TYPES:
    Byte: int
    Ascii: int
    Short: int
    Long: int
    Rational: int
    SByte: int
    Undefined: int
    SShort: int
    SLong: int
    SRational: int
    Float: int
    DFloat: int

TAGS: Incomplete

class ImageIFD:
    ProcessingSoftware: int
    NewSubfileType: int
    SubfileType: int
    ImageWidth: int
    ImageLength: int
    BitsPerSample: int
    Compression: int
    PhotometricInterpretation: int
    Threshholding: int
    CellWidth: int
    CellLength: int
    FillOrder: int
    DocumentName: int
    ImageDescription: int
    Make: int
    Model: int
    StripOffsets: int
    Orientation: int
    SamplesPerPixel: int
    RowsPerStrip: int
    StripByteCounts: int
    XResolution: int
    YResolution: int
    PlanarConfiguration: int
    GrayResponseUnit: int
    GrayResponseCurve: int
    T4Options: int
    T6Options: int
    ResolutionUnit: int
    TransferFunction: int
    Software: int
    DateTime: int
    Artist: int
    HostComputer: int
    Predictor: int
    WhitePoint: int
    PrimaryChromaticities: int
    ColorMap: int
    HalftoneHints: int
    TileWidth: int
    TileLength: int
    TileOffsets: int
    TileByteCounts: int
    SubIFDs: int
    InkSet: int
    InkNames: int
    NumberOfInks: int
    DotRange: int
    TargetPrinter: int
    ExtraSamples: int
    SampleFormat: int
    SMinSampleValue: int
    SMaxSampleValue: int
    TransferRange: int
    ClipPath: int
    XClipPathUnits: int
    YClipPathUnits: int
    Indexed: int
    JPEGTables: int
    OPIProxy: int
    JPEGProc: int
    JPEGInterchangeFormat: int
    JPEGInterchangeFormatLength: int
    JPEGRestartInterval: int
    JPEGLosslessPredictors: int
    JPEGPointTransforms: int
    JPEGQTables: int
    JPEGDCTables: int
    JPEGACTables: int
    YCbCrCoefficients: int
    YCbCrSubSampling: int
    YCbCrPositioning: int
    ReferenceBlackWhite: int
    XMLPacket: int
    Rating: int
    RatingPercent: int
    ImageID: int
    CFARepeatPatternDim: int
    CFAPattern: int
    BatteryLevel: int
    Copyright: int
    ExposureTime: int
    ImageResources: int
    ExifTag: int
    InterColorProfile: int
    GPSTag: int
    Interlace: int
    TimeZoneOffset: int
    SelfTimerMode: int
    FlashEnergy: int
    SpatialFrequencyResponse: int
    Noise: int
    FocalPlaneXResolution: int
    FocalPlaneYResolution: int
    FocalPlaneResolutionUnit: int
    ImageNumber: int
    SecurityClassification: int
    ImageHistory: int
    ExposureIndex: int
    TIFFEPStandardID: int
    SensingMethod: int
    XPTitle: int
    XPComment: int
    XPAuthor: int
    XPKeywords: int
    XPSubject: int
    PrintImageMatching: int
    DNGVersion: int
    DNGBackwardVersion: int
    UniqueCameraModel: int
    LocalizedCameraModel: int
    CFAPlaneColor: int
    CFALayout: int
    LinearizationTable: int
    BlackLevelRepeatDim: int
    BlackLevel: int
    BlackLevelDeltaH: int
    BlackLevelDeltaV: int
    WhiteLevel: int
    DefaultScale: int
    DefaultCropOrigin: int
    DefaultCropSize: int
    ColorMatrix1: int
    ColorMatrix2: int
    CameraCalibration1: int
    CameraCalibration2: int
    ReductionMatrix1: int
    ReductionMatrix2: int
    AnalogBalance: int
    AsShotNeutral: int
    AsShotWhiteXY: int
    BaselineExposure: int
    BaselineNoise: int
    BaselineSharpness: int
    BayerGreenSplit: int
    LinearResponseLimit: int
    CameraSerialNumber: int
    LensInfo: int
    ChromaBlurRadius: int
    AntiAliasStrength: int
    ShadowScale: int
    DNGPrivateData: int
    MakerNoteSafety: int
    CalibrationIlluminant1: int
    CalibrationIlluminant2: int
    BestQualityScale: int
    RawDataUniqueID: int
    OriginalRawFileName: int
    OriginalRawFileData: int
    ActiveArea: int
    MaskedAreas: int
    AsShotICCProfile: int
    AsShotPreProfileMatrix: int
    CurrentICCProfile: int
    CurrentPreProfileMatrix: int
    ColorimetricReference: int
    CameraCalibrationSignature: int
    ProfileCalibrationSignature: int
    AsShotProfileName: int
    NoiseReductionApplied: int
    ProfileName: int
    ProfileHueSatMapDims: int
    ProfileHueSatMapData1: int
    ProfileHueSatMapData2: int
    ProfileToneCurve: int
    ProfileEmbedPolicy: int
    ProfileCopyright: int
    ForwardMatrix1: int
    ForwardMatrix2: int
    PreviewApplicationName: int
    PreviewApplicationVersion: int
    PreviewSettingsName: int
    PreviewSettingsDigest: int
    PreviewColorSpace: int
    PreviewDateTime: int
    RawImageDigest: int
    OriginalRawFileDigest: int
    SubTileBlockSize: int
    RowInterleaveFactor: int
    ProfileLookTableDims: int
    ProfileLookTableData: int
    OpcodeList1: int
    OpcodeList2: int
    OpcodeList3: int
    NoiseProfile: int
    ZZZTestSlong1: int
    ZZZTestSlong2: int
    ZZZTestSByte: int
    ZZZTestSShort: int
    ZZZTestDFloat: int

class ExifIFD:
    ExposureTime: int
    FNumber: int
    ExposureProgram: int
    SpectralSensitivity: int
    ISOSpeedRatings: int
    OECF: int
    SensitivityType: int
    StandardOutputSensitivity: int
    RecommendedExposureIndex: int
    ISOSpeed: int
    ISOSpeedLatitudeyyy: int
    ISOSpeedLatitudezzz: int
    ExifVersion: int
    DateTimeOriginal: int
    DateTimeDigitized: int
    OffsetTime: int
    OffsetTimeOriginal: int
    OffsetTimeDigitized: int
    ComponentsConfiguration: int
    CompressedBitsPerPixel: int
    ShutterSpeedValue: int
    ApertureValue: int
    BrightnessValue: int
    ExposureBiasValue: int
    MaxApertureValue: int
    SubjectDistance: int
    MeteringMode: int
    LightSource: int
    Flash: int
    FocalLength: int
    Temperature: int
    Humidity: int
    Pressure: int
    WaterDepth: int
    Acceleration: int
    CameraElevationAngle: int
    SubjectArea: int
    MakerNote: int
    UserComment: int
    SubSecTime: int
    SubSecTimeOriginal: int
    SubSecTimeDigitized: int
    FlashpixVersion: int
    ColorSpace: int
    PixelXDimension: int
    PixelYDimension: int
    RelatedSoundFile: int
    InteroperabilityTag: int
    FlashEnergy: int
    SpatialFrequencyResponse: int
    FocalPlaneXResolution: int
    FocalPlaneYResolution: int
    FocalPlaneResolutionUnit: int
    SubjectLocation: int
    ExposureIndex: int
    SensingMethod: int
    FileSource: int
    SceneType: int
    CFAPattern: int
    CustomRendered: int
    ExposureMode: int
    WhiteBalance: int
    DigitalZoomRatio: int
    FocalLengthIn35mmFilm: int
    SceneCaptureType: int
    GainControl: int
    Contrast: int
    Saturation: int
    Sharpness: int
    DeviceSettingDescription: int
    SubjectDistanceRange: int
    ImageUniqueID: int
    CameraOwnerName: int
    BodySerialNumber: int
    LensSpecification: int
    LensMake: int
    LensModel: int
    LensSerialNumber: int
    Gamma: int

class GPSIFD:
    GPSVersionID: int
    GPSLatitudeRef: int
    GPSLatitude: int
    GPSLongitudeRef: int
    GPSLongitude: int
    GPSAltitudeRef: int
    GPSAltitude: int
    GPSTimeStamp: int
    GPSSatellites: int
    GPSStatus: int
    GPSMeasureMode: int
    GPSDOP: int
    GPSSpeedRef: int
    GPSSpeed: int
    GPSTrackRef: int
    GPSTrack: int
    GPSImgDirectionRef: int
    GPSImgDirection: int
    GPSMapDatum: int
    GPSDestLatitudeRef: int
    GPSDestLatitude: int
    GPSDestLongitudeRef: int
    GPSDestLongitude: int
    GPSDestBearingRef: int
    GPSDestBearing: int
    GPSDestDistanceRef: int
    GPSDestDistance: int
    GPSProcessingMethod: int
    GPSAreaInformation: int
    GPSDateStamp: int
    GPSDifferential: int
    GPSHPositioningError: int

class InteropIFD:
    InteroperabilityIndex: int
